### PR TITLE
Initial Application & Configuration Ability

### PR DESCRIPTION
**Pull request by dmvt**
##### Description

This PR addresses issue / bounty https://github.com/MARKETProtocol/service-listener/issues/2. It introduces a very bare bones node app that connects to a specified Ethereum network.

##### Checklist

- [X] A new node 8.11.3 LTS project has been created
- [x] A listener daemon has been setup that listens for events on a environment var configurable ethereum network.(Rinkeby, Main, Local Truffle, etc)

##### Affected core subsystem(s)

N/A

##### Screenshots (Optional)

N/A

##### Testing

So far, there's really nothing to test. Based on `PROVIDER`, the network either connects or doesn't:

```
$ npm start
npm WARN lifecycle The node binary used for scripts is /home/dan/.asdf/shims/node but npm is using /home/dan/.asdf/installs/nodejs/8.11.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> service-listener@0.0.1 start /home/dan/local_code/bounties/marketprotocol/service-listener
> node lib/app.js

Connected to http://localhost:9545
```

```
$ PROVIDER=http://localhost:8545 npm start
npm WARN lifecycle The node binary used for scripts is /home/dan/.asdf/shims/node but npm is using /home/dan/.asdf/installs/nodejs/8.11.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> service-listener@0.0.1 start /home/dan/local_code/bounties/marketprotocol/service-listener
> node lib/app.js

Unable to connect to http://localhost:8545
```

##### Refers/Fixes

Refs: https://github.com/MARKETProtocol/service-listener/issues/2

### CODE REVIEW

**Comment by pelsasser** [comment]
@dmvt - this looks great.  Thanks for setting up the README.md as well.

**Comment by eswarasai** [comment]
@dmvt -- Any possibility of setting this app in TypeScript instead of JavaScript? It'll be consistent with the codebase across all our repos except for `dApp`. Thanks!

**Comment by dmvt** [comment]
@eswarasai I can definitely set it up as Typescript, but if no one has any objections I'm going to write it in JS and then convert. This project already includes a lot of firsts for me so I'm trying to minimize the initial cognitive overhead so I can show results quickly.

**Comment by eswarasai** [comment]
@dmvt -- Sure. Feel free to code in the language you're comfortable with but please do keep in mind that it'll be migrated to TypeScript and make changes accordingly. Thanks!

**Comment by dmvt** [comment]
@eswarasai I'm using git master for MARKET.js because we're in active development for this project and MARKET.js is also under heavy churn based on the discord #engineering channel. I prefer to work with latest until my code is being released and then I version lock accordingly.

**Comment by eswarasai** [comment]
@dmvt -- If you're pulling in from `MARKET.js:master`, it's same as using the `^0.1.1`. Moreover, there's no `dist` committed to the GitHub repo. So you won't actually have the build package to work with if you use Git. I hope this makes sense to you.

**Comment by dmvt** [comment]
I think you'll find I'm pretty quick to understand things in general @eswarasai :). Thanks for explaining!

**Comment by eswarasai** [comment]
@dmvt -- I'm counting on it 😉 Just wanted to make sure you're not stuck and also have an idea about few issues we've already faced in the project :)

**Comment by rojosnow** [comment]
Beepity, bot... ;)

**Pull request merged**
